name: qpv_client_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_map:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
    # Device type
  flutter_device_type: ^0.2.0
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  fleva_icons: ^1.0.2
    # Model Progress HUD
  modal_progress_hud: ^0.1.3
    # Spinner
  flutter_spinkit: ^3.1.0
  shared_preferences: ^0.5.3+4
    # provider
  provider: ^3.0.0+1
  simple_animations: ^2.2.1
  sa_multi_tween: ^1.1.1
    #timeline_tile
  timeline_tile: ^1.0.0

  camera: ^0.5.8+11
  image: ^2.1.12
  quiver: ^2.1.5
  path_provider: ^1.6.11

  image_picker: ^0.6.7+14
  http: ^0.12.0+2
  json_annotation: ^2.2.0
  firebase_ml_vision: ^0.9.9
  firebase_core : ^0.5.0
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  carousel_pro: ^1.0.0
  flutter_facebook_login: ^3.0.0
  firebase_storage: ^5.0.1
  firebase_messaging: ^7.0.3
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.7
  flutter_polyline_points: ^0.2.4
  geocoding: ^1.0.4
  maps_launcher: ^1.2.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  uses-material-design: true
  assets:
    - res/images/

  fonts:

    - family: RubikBold
      fonts:
        - asset: res/fonts/Rubik-Bold.ttf

    - family: Rubik
      fonts:
        - asset: res/fonts/Rubik-Regular.ttf

    - family: RubikMedium
      fonts:
        - asset: res/fonts/Rubik-Medium.ttf

    - family: RubikSemiBold
      fonts:
        - asset: res/fonts/Rubik-SemiBold.ttf
